version: "3.7"
services:
  mongodb:
    image: mongo
    container_name: csvquery_mongodb
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
#    ports:
#      - 27017:27017
#  mongo-express:
#    image: mongo-express
#    container_name: csvquery_mongo_express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=username
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
#      - ME_CONFIG_MONGODB_SERVER=csvquery_mongodb
  csvquery:
    image: andreicimpoca/csvrecord:1.0.0
    container_name: csvquery
    restart: always
    command: --spring.data.mongodb.host=csvquery_mongodb
    ports:
      - 8080:8080
networks:
  default:
    name: csvquery
volumes:
  data: {}
